package:
    name: esgf_thredds
    version: "4.0a1"

source:
    - url: ./commons-httpclient-3.1.jar
    - url: ./commons-lang-2.6.jar
    - url: ./jdom-legacy-1.1.3.jar

build:
  number: 0
  noarch: generic


requirements:
  build:
    - python
    - curl
  run:
    - python

about:
    home:  http://esgf.llnl.gov
    summary: Thredds jars
